"""SQLAlchemy ORM models for Frontier AI Radar local SQLite database."""

from datetime import datetime, timezone
from sqlalchemy import (
    Boolean,
    Column,
    Integer,
    String,
    Text,
    LargeBinary,
    DateTime,
    ForeignKey,
    CheckConstraint,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""
    pass


class Extraction(Base):
    """Stores basic information before passing it to the next stages."""

    __tablename__ = "extractions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    publication_date = Column(DateTime, nullable=True)
    mode = Column(String(10), CheckConstraint("mode IN ('job', 'UI')"), nullable=True)
    metadata_ = Column("metadata", Text, nullable=True)  # JSON as TEXT
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    findings = relationship("Finding", back_populates="extraction", cascade="all, delete-orphan")
    runs = relationship("Run", back_populates="extraction")

    def __repr__(self) -> str:
        return f"<Extraction id={self.id} mode={self.mode} created_at={self.created_at}>"


class Finding(Base):
    """Stores high-impact summaries, scores, and content generated by agents."""

    __tablename__ = "findings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    extraction_id = Column(Integer, ForeignKey("extractions.id", ondelete="CASCADE"), nullable=False)
    agent_name = Column(String(20), nullable=False)  # research, competitor, model, benchmark
    html_content = Column(Text, nullable=True)
    pdf_content = Column(LargeBinary, nullable=True)
    metadata_ = Column("metadata", Text, nullable=True)  # JSON as TEXT

    # Relationships
    extraction = relationship("Extraction", back_populates="findings")

    def __repr__(self) -> str:
        return f"<Finding id={self.id} agent={self.agent_name} extraction_id={self.extraction_id}>"


class Run(Base):
    """Tracks history, status, and performance of each system execution."""

    __tablename__ = "runs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    extraction_id = Column(Integer, ForeignKey("extractions.id", ondelete="SET NULL"), nullable=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    status = Column(String(20), nullable=True)  # success, failure, partial_failure
    time_taken = Column(Integer, nullable=True)  # duration in seconds
    started_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    pdf_path = Column(Text, nullable=True)  # filesystem path for reference
    pdf_content = Column(LargeBinary, nullable=True)  # actual PDF bytes

    # Relationships
    extraction = relationship("Extraction", back_populates="runs")
    user = relationship("User", back_populates="runs")
    resources = relationship("Resource", back_populates="run", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Run id={self.id} status={self.status} time_taken={self.time_taken}s>"


class User(Base):
    """Subscribed users who receive digest emails."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(200), nullable=False)
    email = Column(String(320), nullable=False, unique=True)
    subscribed_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    runs = relationship("Run", back_populates="user")

    def __repr__(self) -> str:
        return f"<User id={self.id} name={self.name} email={self.email}>"


class Resource(Base):
    """Tracks every source URL / name discovered by each agent per run."""

    __tablename__ = "resources"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(Integer, ForeignKey("runs.id", ondelete="CASCADE"), nullable=False)
    agent_name = Column(String(20), nullable=False)  # research, competitor, model, benchmark
    name = Column(String(500), nullable=False)
    url = Column(Text, nullable=True)
    resource_type = Column(String(50), nullable=True)  # paper, model_card, blog, leaderboard, dataset, release_note
    discovered_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    run = relationship("Run", back_populates="resources")

    def __repr__(self) -> str:
        return f"<Resource id={self.id} agent={self.agent_name} name={self.name[:40]}>"


class Competitor(Base):
    """
    Competitor source URLs used by the Competitor Intelligence Agent.

    Pre-seeded with defaults on first deploy; users can add extra sources
    via POST /competitors.
    """

    __tablename__ = "competitors"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(200), nullable=False)          # "OpenAI Blog", "Anthropic News", etc.
    url = Column(Text, nullable=False, unique=True)     # RSS/webpage URL
    source_type = Column(String(20), nullable=False)    # "rss" | "webpage"
    selector = Column(String(200), nullable=True)       # CSS selector (only for webpage type)
    is_default = Column(Boolean, default=True)          # TRUE = seeded on deploy
    is_active = Column(Boolean, default=True)           # toggle without deleting
    added_by = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    user = relationship("User")

    def __repr__(self) -> str:
        return f"<Competitor id={self.id} name={self.name} active={self.is_active}>"
