/**
 * Dummy data for Frontier AI Radar APIs. Replace with real backend when integrating.
 */

import type { AgentId, Finding, Run, Source, Digest } from "./types";

export const DUMMY_SOURCES: Source[] = [
  { id: "src-1", url: "https://openai.com/blog", agent_id: "competitor", label: "OpenAI Blog", created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-06T00:00:00Z" },
  { id: "src-2", url: "https://anthropic.com/news", agent_id: "foundation", label: "Anthropic News", created_at: "2026-03-01T00:00:00Z", updated_at: "2026-03-06T00:00:00Z" },
  { id: "src-3", url: "https://huggingface.co/spaces/leaderboards", agent_id: "huggingface", label: "HF Leaderboards", created_at: "2026-03-02T00:00:00Z", updated_at: "2026-03-06T00:00:00Z" },
];

export const DUMMY_RUNS: Run[] = [
  { id: "run-001", status: "completed", started_at: "2026-03-06T10:32:00Z", finished_at: "2026-03-06T10:38:00Z", source_url: "openai.com", agent_ids: ["competitor", "foundation"], recipient_emails: ["alice@example.com", "bob@example.com"], findings_count: 12 },
  { id: "run-002", status: "completed", started_at: "2026-03-05T15:15:00Z", finished_at: "2026-03-05T15:22:00Z", source_url: "anthropic.com", agent_ids: ["competitor", "research", "huggingface"], recipient_emails: ["team@company.com"], findings_count: 8 },
  { id: "run-003", status: "failed", started_at: "2026-03-04T09:00:00Z", source_url: "mistral.ai", agent_ids: ["competitor", "huggingface"], recipient_emails: [], error_message: "Connection timeout", agent_errors: [{ agent_id: "huggingface", message: "Rate limit exceeded" }] },
];

export const DUMMY_FINDINGS: Finding[] = [
  { id: "f1", title: "GPT-4o API general availability", date_detected: "2026-03-06", source_url: "https://openai.com/blog/gpt-4o-api", publisher: "OpenAI", agent_id: "competitor", category: "release", summary_short: "GPT-4o API is now generally available with lower latency and extended context.", summary_long: "OpenAI announced GA for GPT-4o API. Key changes: 50% lower latency, 128K context, vision and tool use.", why_it_matters: "Enables production workloads at scale.", evidence: "Official blog, March 6.", confidence: 0.95, tags: ["api", "gpt-4o"], entities: ["OpenAI", "GPT-4o"], impact_score: 0.88 },
  { id: "f2", title: "Claude 3.5 Sonnet pricing update", date_detected: "2026-03-05", source_url: "https://anthropic.com/pricing", publisher: "Anthropic", agent_id: "foundation", category: "pricing", summary_short: "Anthropic reduced input pricing for Claude 3.5 Sonnet by 20%.", summary_long: "Pricing update effective March 5. Input $3/M tokens, output $15/M.", why_it_matters: "Lower cost for high-volume use cases.", evidence: "Pricing page.", confidence: 0.98, tags: ["pricing", "claude"], entities: ["Anthropic", "Claude 3.5"], impact_score: 0.72 },
  { id: "f3", title: "New SOTA on MMLU", date_detected: "2026-03-06", source_url: "https://huggingface.co/spaces/leaderboards", publisher: "Hugging Face", agent_id: "huggingface", category: "benchmark", summary_short: "Model X reached 92.1% on MMLU, leading the leaderboard.", summary_long: "Weekly leaderboard update. Model X (open weights) leads MMLU and GSM8K.", why_it_matters: "Open models closing gap with frontier.", evidence: "HF Leaderboard snapshot.", confidence: 0.85, tags: ["benchmark", "MMLU"], entities: ["Model X"], impact_score: 0.81 },
  { id: "f4", title: "Agentic workflow paper (arXiv)", date_detected: "2026-03-04", source_url: "https://arxiv.org/abs/xxxx.xxxxx", publisher: "arXiv", agent_id: "research", category: "research", summary_short: "New methodology for multi-step agent reasoning with tool use.", summary_long: "Paper proposes a training approach that improves agent tool use and planning.", why_it_matters: "Relevant for agentic product roadmaps.", evidence: "arXiv abstract.", confidence: 0.78, tags: ["agents", "reasoning"], entities: [], impact_score: 0.65 },
  { id: "f5", title: "OpenAI DevDay recap", date_detected: "2026-03-06", source_url: "https://openai.com/blog", publisher: "OpenAI", agent_id: "competitor", category: "release", summary_short: "Recap of new Assistants API and batch endpoints.", summary_long: "Assistants API updates, batch API for cost savings, new models in playground.", why_it_matters: "Direct impact on integration strategy.", evidence: "Blog post.", confidence: 0.92, tags: ["api", "assistants"], entities: ["OpenAI"], impact_score: 0.79 },
  { id: "f6", title: "Gemini 1.5 Flash expansion", date_detected: "2026-03-05", source_url: "https://blog.google", publisher: "Google", agent_id: "foundation", category: "release", summary_short: "Gemini 1.5 Flash available in 200+ countries with new modalities.", summary_long: "Expanded availability and audio/video input support.", why_it_matters: "Broader access to multimodal APIs.", evidence: "Official blog.", confidence: 0.9, tags: ["gemini", "multimodal"], entities: ["Google", "Gemini"], impact_score: 0.74 },
  { id: "f7", title: "Safety evals benchmark", date_detected: "2026-03-03", source_url: "https://arxiv.org/abs/yyyy.yyyyy", publisher: "arXiv", agent_id: "research", category: "research", summary_short: "Benchmark for safety and alignment evaluations.", summary_long: "Dataset and metrics for red-teaming and policy compliance.", why_it_matters: "Standardization for safety reporting.", evidence: "arXiv.", confidence: 0.82, tags: ["safety", "eval"], entities: [], impact_score: 0.58 },
  { id: "f8", title: "Coding leaderboard update", date_detected: "2026-03-06", source_url: "https://huggingface.co/spaces/leaderboards", publisher: "Hugging Face", agent_id: "huggingface", category: "benchmark", summary_short: "SWE-bench and HumanEval leaderboards updated.", summary_long: "Several models improved on SWE-bench; small models gained on HumanEval.", why_it_matters: "Tracking coding capability trends.", evidence: "HF spaces.", confidence: 0.88, tags: ["coding", "benchmark"], entities: [], impact_score: 0.62 },
  { id: "f9", title: "API rate limit increase", date_detected: "2026-03-05", source_url: "https://openai.com/docs", publisher: "OpenAI", agent_id: "foundation", category: "api", summary_short: "Tier 2 default rate limits increased for GPT-4o.", summary_long: "RPM and TPM limits raised for production tiers.", why_it_matters: "Fewer throttling issues at scale.", evidence: "Docs changelog.", confidence: 0.94, tags: ["api", "rate-limit"], entities: ["OpenAI"], impact_score: 0.68 },
  { id: "f10", title: "Multimodal reasoning survey", date_detected: "2026-03-02", source_url: "https://arxiv.org/abs/zzzz.zzzzz", publisher: "arXiv", agent_id: "research", category: "research", summary_short: "Survey of multimodal reasoning and chain-of-thought.", summary_long: "Comprehensive overview of techniques and benchmarks.", why_it_matters: "Reference for R&D planning.", evidence: "arXiv.", confidence: 0.75, tags: ["multimodal", "reasoning"], entities: [], impact_score: 0.55 },
];

export const DUMMY_DIGESTS: Digest[] = [
  { id: "dig-001", run_id: "run-001", date: "2026-03-06", executive_summary: "Today's digest covers OpenAI GPT-4o API GA, Anthropic pricing, and HF leaderboard updates.", findings_count: 12, pdf_url: "/api/digests/dig-001/pdf", created_at: "2026-03-06T10:38:00Z" },
  { id: "dig-002", run_id: "run-002", date: "2026-03-05", executive_summary: "Claude pricing update, Gemini expansion, and research highlights.", findings_count: 8, pdf_url: "/api/digests/dig-002/pdf", created_at: "2026-03-05T15:22:00Z" },
];
